{{- if .Values.nodered.enabled -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "factorycube-server.fullname" . }}-nodered-claim
  labels:
    {{- include "factorycube-server.labels.nodered" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nodered.storageRequest }}

{{- end }}
