{{- if .Values.timescaledb.enabled -}}

apiVersion: v1
kind: secret 
metadata:  
  name: timescale-post-init-pw 
data:  
  0_set_passwords.sh: |-
    #!/bin/bash

    psql -d "$1" <<__SQL__

    SET log_statement TO none;      -- prevent these passwords from being logged
    ALTER USER {{ .Values.grafana.db_user }} WITH PASSWORD '{{ .Values.grafana.db_password }}';
    ALTER USER {{ .Values.factoryinsight.db_user }} WITH PASSWORD '{{ .Values.factoryinsight.db_password }}';
    __SQL__
{{- end -}}
