{{- if .Values.vernemq.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorycube-server.fullname" . }}-vernemq-local-service
  labels:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
    app.kubernetes.io/managed-by: helm 
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
      app.kubernetes.io/instance: vernemq
      app.kubernetes.io/name: vernemq
  {{- end -}}
