
{{- if .Values.ubuntu.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorycube-core.fullname" . }}-ubuntu-claim
  labels:
    {{- include "factorycube-core.labels.ubuntu" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.ubuntu.port }}
      targetPort: {{ .Values.ubuntu.port }}
      protocol: TCP
      name: custom
    - port: 8022
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
      {{- include "factorycube-core.labels.ubuntu" . | nindent 6 }}

{{- end }}
